package com.neeyamo.approvalflow.pojo;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Proxy;

/**
 * TbDataFlowApplicationTransLogs generated by hbm2java
 */
@Entity
@Proxy(lazy = false)
@Table(name = "tb_approval_trans_log")
public class TbApprovalTransLog implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)

	private Long approvalTransLogId;
	private String applicationCode;
	private String applicationName;
	private String appEvents;
	private String actionItems;
	private String transactionId;
	private String employeeId;
	private String employeeName;
	private String applicationData;
	private String status;
	private String assignedBy;
	private String assignedTo;
	private String createdBy;
	private Date createdOn;
	private String updatedBy;
	private Date updatedOn;
	private Boolean isActive;

	public TbApprovalTransLog() {
	}

	public TbApprovalTransLog(Long approvalTransLogId) {
		this.approvalTransLogId = approvalTransLogId;
	}

	@Column(name = "approvalTransLogId", unique = true, nullable = false)
	public Long getApprovalTransLogId() {
		return this.approvalTransLogId;
	}

	public void setApprovalTransLogId(Long approvalTransLogId) {
		this.approvalTransLogId = approvalTransLogId;
	}

	@Column(name = "applicationCode", length = 100)
	public String getApplicationCode() {
		return this.applicationCode;
	}

	public void setApplicationCode(String applicationCode) {
		this.applicationCode = applicationCode;
	}

	@Column(name = "applicationName", length = 100)
	public String getApplicationName() {
		return this.applicationName;
	}

	public void setApplicationName(String applicationName) {
		this.applicationName = applicationName;
	}

	@Column(name = "appEvents", length = 100)
	public String getAppEvents() {
		return appEvents;
	}

	public void setAppEvents(String appEvents) {
		this.appEvents = appEvents;
	}

	@Column(name = "actionItems", length = 100)
	public String getActionItems() {
		return actionItems;
	}

	public void setActionItems(String actionItems) {
		this.actionItems = actionItems;
	}

	@Column(name = "transactionId", length = 100)
	public String getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}

	@Column(name = "employeeId", length = 100)
	public String getEmployeeId() {
		return employeeId;
	}

	public void setEmployeeId(String employeeId) {
		this.employeeId = employeeId;
	}

	@Column(name = "employeeName", length = 100)
	public String getEmployeeName() {
		return employeeName;
	}

	public void setEmployeeName(String employeeName) {
		this.employeeName = employeeName;
	}

	@Column(name = "applicationData")
	public String getApplicationData() {
		return applicationData;
	}

	public void setApplicationData(String applicationData) {
		this.applicationData = applicationData;
	}

	@Column(name = "status", length = 100)
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "assignedBy", length = 100)
	public String getAssignedBy() {
		return assignedBy;
	}

	public void setAssignedBy(String assignedBy) {
		this.assignedBy = assignedBy;
	}

	@Column(name = "assignedTo", length = 100)
	public String getAssignedTo() {
		return assignedTo;
	}

	public void setAssignedTo(String assignedTo) {
		this.assignedTo = assignedTo;
	}

	@Column(name = "createdBy", length = 200)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdOn", length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "updatedBy", length = 200)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updatedOn", length = 19)
	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

	@Column(name = "isActive")
	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

}
